# Generated by Django 5.0.2 on 2024-02-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_email'),
    ]

    operations = [
    ]
