# Generated by Django 5.0.2 on 2024-02-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_company_email_company_is_active_company_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
